# DESCRIPTION: Travis-CI config
#
# Copyright 2003-2020 by Wilson Snyder. This program is free software; you
# can redistribute it and/or modify it under the terms of either the GNU
# Lesser General Public License Version 3 or the Perl Artistic License
# Version 2.0.
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

version: ~> 1.0

#os: linux
os: osx
osx_image: xcode11.4
language: cpp
cache: ccache

env:
  global:
    - VERILATOR_CACHE=$HOME/verilator_cache
    - VERILATOR_ROOT=$PWD
    - VERILATOR_NUM_JOBS=$(echo `nproc` + 1 | bc)
    - VERILATOR_CONFIG_FLAGS="--enable-maintainer-mode --enable-longtests"
    - VERILATOR_AUTHOR_SITE=1

cache:
  directories:
    - $VERILATOR_CACHE

before_install:
# Perl modules needed for testing
# Not listing Bit::Vector as slow to install, and only skips one test
  - touch temp.cpp ; g++ -E -dM -c temp.cpp | sort ; rm -rf temp.cpp
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew update
      brew install bison flex
      PATH=/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:$PATH
      export LDFLAGS="-L/usr/local/opt/bison/lib"
      export LDFLAGS="-L/usr/local/opt/flex/lib"
      export CPPFLAGS="-I/usr/local/opt/flex/include"
    fi
before_script:
  - bash -x ci/build_vcddiff.sh
  - bash -x ci/build_verilator.sh
after_script:
  - ccache -s

stages:
  - "Build Verilator"
  - test

jobs:
  include:
    - os: osx
      osx_image: xcode11.4
      stage: "Build Verilator"
      name: "Build Verilator"
      script: echo "Done building Verilator"
